name: Caching files
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-file${{ hashFiles('**/package-lock.json') }} # linux-npm-cache-file-4356566
          restore-keys: |
            ${{ runner.os }}-npm-cache-file
            ${{ runner.os }}-
      - name: Cache output display
        run: echo '${{ toJSON(steps.cache-dependencies.outputs) }}'
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: code-coverage
          path: coverage
          retention-days: 10
      - name: Download Code Coverage Report
        uses: actions/download-artifact@v3
        with:
          name: code-coverage
          path: code-coverage-report
      - run: ls -a
      - run: ls -a
        working-directory: code-coverage-report
     