name: Manually Triggered
on:
  workflow_dispatch:
    inputs:
      string:
        description: Enter Description
        type: string
        required: true
        default: "Manually triggered using GitHub actions GUI"
      environment:
        description: "Environment"
        type: environment
        required: true

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF
      - run: |
          echo "String: ${{ inputs.string }}"
          echo "Environment: ${{ inputs.environment }}"